name: Python Generation Tests

on:
  push:
    branches: [ main, lua-tests ]
    paths:
        - '**'
        - '!**/*.md'
        - '!.github/workflows/*.yml'
        - '.github/workflows/python-tests.yml'

  pull_request:
    branches: [ main ]
    paths:
        - '**'
        - '!**/*.md'
        - '!.github/workflows/*.yml'
        - '.github/workflows/python-tests.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java-version: ['17', '21']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'adopt'
    - name: Create test directories (POSIX)
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        mkdir -p ~/bin ~/logs
    - name: Create test directories (Windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        $dirs = "${env:USERPROFILE}/bin", "${env:USERPROFILE}/logs"
        foreach ($d in $dirs) {
          if (!(test-path $d)) {
            mkdir $d
          }
        }
    - name: Cache Jython (POSIX)
      if: ${{ (matrix.os != 'windows-latest') }}
      id: cache-jython-posix
      uses: actions/cache@v3
      with:
        path: ~/bin/jython.jar
        key: ${{ runner.os }}-jython
    - name: Setup Jython 2.7.2 (POSIX)
      if: ${{ (matrix.os != 'windows-latest') && (steps.cache-jython-posix.outputs.cache-hit != 'true') }}
      run: |
        wget https://repo1.maven.org/maven2/org/python/jython-standalone/2.7.2/jython-standalone-2.7.2.jar -O ~/bin/jython.jar
    - name: Cache Jython (Windows)
      if: ${{ (matrix.os == 'windows-latest') }}
      id: cache-jython-windows
      uses: actions/cache@v3
      with:
        path: ${env:USERPROFILE}/bin/jython.jar
        key: ${{ runner.os }}-jython
    - name: Setup Jython 2.7.2 (Windows)
      # Windows cache check temporarily disabled, as on Windows you can't restore to the correct location
      #if: ${{ matrix.os == 'windows-latest' && (steps.cache-jython-windows.outputs.cache-hit != 'true') }}
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        $source = 'https://repo1.maven.org/maven2/org/python/jython-standalone/2.7.2/jython-standalone-2.7.2.jar'
        $destination = "${env:USERPROFILE}/bin/jython.jar"
        Invoke-WebRequest -Uri $source -OutFile $destination
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Run tests
      run: |
        java -jar $HOME/bin/jython.jar --version
        python --version
        ant -version
        ant test-python
      env:
        PY_DEBUG: 1
